### ISSUE TITLE
[Errno 19] ENODEV - micropython: 07-i2c-test.py

### ISSUE THREAD

**Issue by octopusengine** [octopusengine/octopuslab#6]
i2c test PCF > [Errno 19] ENODEV

**Comment by petrkr** [comment]
Try use pull-up resistors on i2c lines and slow down communication to 100kHz (default is 400kHz). Regarding to PCF datasheet, it's maximum I2C timings is 100kHz on SCL line

**Comment by petrkr** [comment]
Check commit 3ab1d23b7a7dcee9f45bc066861d5d0abadfaa97

**Comment by petrkr** [comment]
Fixed by 4b59c27
